# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: 
      - main 

  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

     
      - name: Set permission for BUILD.sh
        run: chmod 777 ./BUILD.sh
        
      - name: Set permission for TEST.sh
        run: chmod 777 ./TEST.sh
        
      - name: Start BUILD.sh
        run: ./BUILD.sh   
      
      - name: Start TEST.sh
        run: ./TEST.sh
      
         
